version: "3.8"
services:
  addresses-mock-server:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 1090
    ports:
      - 8010:1090
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
    volumes:
      - ./addresses/config:/config

  coches-automotive-mock-server:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 1090
    ports:
      - 8011:1090
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
    volumes:
      - ./automotive-makes/coches/config:/config

  motos-automotive-mock-server:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 1090
    ports:
      - 8012:1090
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
    volumes:
      - ./automotive-makes/motos/config:/config

  customers-mock-server:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 1090
    ports:
      - 8020:1090
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
    volumes:
      - ./customers/config:/config

  orders-mock-server:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 1090
    ports:
      - 8030:1090
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
    volumes:
      - ./orders/config:/config
